version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_media_files: {}

services:
  django:
    build:
      context: ./smdb
      dockerfile: ./compose/debug/django/Dockerfile
    image: smdb_debug_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
    volumes:
      # Edit source path to use directories from *your* host
      - /Users/mccann/docker_smdb_vol:/etc/smdb:z
      - /Users/mccann/.ssh:/root/.ssh:z
      # Mount smb://titan.shore.mbari.org/SeafloorMapping on your Mac
      - /Volumes/SeafloorMapping:/mbari/SeafloorMapping:z
      - .:/app:z
      - local_media_files:/media:z
    env_file:
      - ./smdb/.envs/.local/.django
      - ./smdb/.envs/.local/.postgres
    ports:
      # VS Code debug launch uses 8000, command: /start uses 8001
      - "8000:8000"
      - "8001:8001"
    command: /start

  postgres:
    build:
      context: ./smdb
      dockerfile: ./compose/production/postgres/Dockerfile
    image: smdb_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./smdb/.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  mb-system:
    image: mbari/mbsystem:latest
    container_name: mb-system
    volumes:
      # Edit source path to use directories from *your* host
      # Copy your public key to your ~/.ssh/authorized_keys file
      - /Users/mccann/.ssh:/root/.ssh:z
      - /Volumes/SeafloorMapping:/mbari/SeafloorMapping:z
    command: /usr/sbin/sshd -D

  nginx:
    image: smdb_debug_nginx
    build:
        context: ./smdb
        dockerfile: compose/debug/nginx/Dockerfile
    container_name: nginx
    volumes:
      # Requires configured nginx user to have read permissions
      - /Volumes/SeafloorMapping:/usr/share/nginx/html/SeafloorMapping:ro
    ports:
      - "80:80"
