# Generated by Django 3.1.10 on 2021-06-30 21:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import smdb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(db_index=True, max_length=256)),
                ('full_reference', models.CharField(db_index=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compilation_dir_name', models.CharField(db_index=True, max_length=128)),
                ('grid_bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('compilation_path_name', models.CharField(db_index=True, max_length=128)),
                ('navadjust_dir_path', models.CharField(db_index=True, max_length=128)),
                ('figures_dir_path', models.CharField(db_index=True, max_length=128)),
                ('comment', models.TextField(blank=True, null=True)),
                ('thumbnail_filename', models.CharField(db_index=True, max_length=128)),
                ('kml_filename', models.CharField(db_index=True, max_length=128)),
                ('proc_datalist_filename', models.CharField(db_index=True, max_length=128)),
                ('update_status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataArchival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(db_index=True, max_length=256)),
                ('archival_db_name', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', smdb.models.UUIDField(editable=False, max_length=32)),
                ('expd_name', models.CharField(max_length=128, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('expd_path_name', models.CharField(max_length=256, null=True)),
                ('expd_db_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', smdb.models.UUIDField(editable=False, max_length=32)),
                ('mission_name', models.CharField(db_index=True, max_length=128)),
                ('grid_bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('start_depth', models.FloatField(blank=True, null=True)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('quality_comment', models.TextField(blank=True, null=True)),
                ('repeat_survey', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('notes_filename', models.CharField(db_index=True, max_length=128)),
                ('region_name', models.CharField(db_index=True, max_length=128)),
                ('site_detail', models.CharField(db_index=True, max_length=128)),
                ('thumbnail_filename', models.CharField(db_index=True, max_length=128)),
                ('kml_filename', models.CharField(db_index=True, max_length=128)),
                ('update_status', models.IntegerField(blank=True, null=True)),
                ('citations', models.ManyToManyField(blank=True, to='smdb.Citation')),
                ('compilation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smdb.compilation')),
                ('data_archivals', models.ManyToManyField(blank=True, to='smdb.DataArchival')),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smdb.expedition')),
            ],
        ),
        migrations.CreateModel(
            name='MissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', smdb.models.UUIDField(editable=False, max_length=32)),
                ('mission_type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', smdb.models.UUIDField(editable=False, max_length=32)),
                ('first_name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('last_name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('institution_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PlatformType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', smdb.models.UUIDField(editable=False, max_length=32)),
                ('platform_type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', smdb.models.UUIDField(editable=False, max_length=32)),
                ('sensor_type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=128)),
                ('missions', models.ManyToManyField(to='smdb.Mission')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smdb.sensortype')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', smdb.models.UUIDField(editable=False, max_length=32)),
                ('platform_name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('operator_org_name', models.CharField(blank=True, max_length=128, null=True)),
                ('platform_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smdb.platformtype')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smdb.missiontype'),
        ),
        migrations.AddField(
            model_name='mission',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smdb.platform'),
        ),
        migrations.AddField(
            model_name='mission',
            name='sensors',
            field=models.ManyToManyField(to='smdb.Sensor'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='chiefscientist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chiefscientist', to='smdb.person'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigator', to='smdb.person'),
        ),
        migrations.AddField(
            model_name='dataarchival',
            name='missions',
            field=models.ManyToManyField(to='smdb.Mission'),
        ),
        migrations.AddField(
            model_name='citation',
            name='missions',
            field=models.ManyToManyField(to='smdb.Mission'),
        ),
    ]
