# Generated by Django 3.1.10 on 2021-07-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
