# Generated by Django 3.1.10 on 2021-07-31 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0002_auto_20210703_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='notes_filename',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smdb.mission')),
            ],
        ),
    ]
