# Generated by Django 3.2.6 on 2021-08-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0003_auto_20210731_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_type',
            new_name='missiontype',
        ),
        migrations.RenameField(
            model_name='missiontype',
            old_name='mission_type_name',
            new_name='missiontype_name',
        ),
    ]
