# Generated by Django 3.2.6 on 2021-08-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0006_auto_20210809_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformtype',
            old_name='platform_type_name',
            new_name='platformtype_name',
        ),
    ]
