# Generated by Django 3.2.6 on 2021-08-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0008_auto_20210821_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontype',
            name='missiontype_name',
            field=models.CharField(max_length=128),
        ),
    ]
