# Generated by Django 3.2.6 on 2021-08-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0010_alter_missiontype_missiontype_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyValue',
        ),
    ]
