# Generated by Django 3.2.6 on 2021-08-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0011_delete_keyvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensortype',
            old_name='sensor_type_name',
            new_name='sensortype_name',
        ),
    ]
