# Generated by Django 3.2.6 on 2021-09-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0013_auto_20210903_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='smdb.Sensor'),
        ),
    ]
