# Generated by Django 3.2.6 on 2021-09-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0014_alter_mission_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='kml_filename',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
