# Generated by Django 3.2.6 on 2021-09-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0016_auto_20210909_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformtype',
            old_name='platformtype_name',
            new_name='name',
        ),
    ]
