# Generated by Django 3.2.6 on 2021-09-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0017_rename_platformtype_name_platformtype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='platform_name',
            new_name='name',
        ),
    ]
