# Generated by Django 3.2.6 on 2021-09-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0018_rename_platform_name_platform_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missiontype',
            old_name='missiontype_name',
            new_name='name',
        ),
    ]
