# Generated by Django 3.2.6 on 2021-09-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0019_rename_missiontype_name_missiontype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensortype',
            old_name='sensortype_name',
            new_name='name',
        ),
    ]
