# Generated by Django 3.2.6 on 2021-09-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0020_rename_sensortype_name_sensortype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedition',
            old_name='expd_name',
            new_name='name',
        ),
    ]
