# Generated by Django 3.2.6 on 2021-09-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0021_rename_expd_name_expedition_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compilation',
            old_name='compilation_dir_name',
            new_name='dir_name',
        ),
        migrations.RenameField(
            model_name='compilation',
            old_name='compilation_path_name',
            new_name='path_name',
        ),
    ]
