# Generated by Django 3.2.6 on 2021-09-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0022_auto_20210909_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_name',
            new_name='name',
        ),
    ]
