# Generated by Django 3.2.7 on 2021-09-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0024_alter_expedition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='thumbnail_url',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
