# Generated by Django 3.2.7 on 2021-09-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0026_mission_tumbnail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='tumbnail_image',
            new_name='thumbnail_image',
        ),
    ]
