# Generated by Django 3.2.7 on 2021-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0027_rename_tumbnail_image_mission_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='app/smdb/smdb/media/thumbnails'),
        ),
    ]
