# Generated by Django 3.2.7 on 2021-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0029_auto_20210915_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='thumbnail_image',
            field=models.ImageField(blank=True, max_length=128, upload_to='thumbnails'),
        ),
    ]
