# Generated by Django 3.2.7 on 2021-09-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0030_alter_mission_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='notes_filename',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='thumbnail_filename',
            field=models.CharField(blank=True, db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='mission',
            name='thumbnail_image',
            field=models.ImageField(blank=True, max_length=256, upload_to='thumbnails'),
        ),
    ]
