# Generated by Django 3.2.7 on 2021-09-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0031_auto_20210917_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='expd_path_name',
        ),
        migrations.AddField(
            model_name='mission',
            name='directory',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
