# Generated by Django 3.2.7 on 2021-09-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0032_auto_20210924_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='notes_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
