# Generated by Django 3.2.7 on 2021-09-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smdb", "0033_auto_20210929_0543"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedition",
            name="slug",
            field=models.SlugField(default="not-set", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mission",
            name="slug",
            field=models.SlugField(default="not-set", max_length=256),
            preserve_default=False,
        ),
    ]
