# Generated by Django 3.2.7 on 2021-10-01 05:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0034_auto_20210930_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='nav_track',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
