# Generated by Django 3.2.8 on 2021-12-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0035_mission_nav_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='dont_use_survey',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='failed_survey',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='patch_test',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='test_survey',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='use_survey_with_caution',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
