# Generated by Django 3.2.11 on 2022-02-01 01:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0037_mission_track_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilationMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('compilation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smdb.compilation')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smdb.mission')),
            ],
            options={
                'verbose_name': 'Compilation Mission',
                'verbose_name_plural': 'Compilation Missions',
                'unique_together': {('compilation', 'mission')},
            },
        ),
    ]
