# Generated by Django 3.2.11 on 2022-02-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0038_compilationmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compilation',
            old_name='dir_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='compilation',
            name='missions',
            field=models.ManyToManyField(related_name='compilations', to='smdb.Mission'),
        ),
        migrations.DeleteModel(
            name='CompilationMission',
        ),
    ]
