# Generated by Django 3.2.11 on 2022-02-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0040_compilation_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='cmd_filename',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to=''),
        ),
    ]
