# Generated by Django 3.2.11 on 2022-02-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0042_compilation_grd_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='cmd_filename',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='comment',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='creation_date',
            field=models.DateTimeField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='figures_dir_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='grd_filename',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='kml_filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='navadjust_dir_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='path_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='proc_datalist_filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='thumbnail_filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
