# Generated by Django 3.2.11 on 2022-02-03 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0043_auto_20220202_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
