# Generated by Django 3.2.11 on 2022-02-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdb', '0044_compilation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='thumbnail_image',
            field=models.ImageField(blank=True, max_length=256, upload_to='thumbnails'),
        ),
    ]
