# Generated by Django 4.2.9 on 2024-05-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smdb", "0046_remove_mission_compilation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="route_file",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
