# Generated by Django 4.2.9 on 2024-05-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smdb", "0047_mission_route_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="auv",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="lass",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="mgds_compilation",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="status",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="vehicle_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
