# Generated by Django 4.2.9 on 2024-05-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smdb", "0048_mission_auv_mission_lass_mission_mgds_compilation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="start_depth",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="track_length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
    ]
