# Generated by Django 4.2.9 on 2024-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smdb", "0049_alter_mission_start_depth_alter_mission_track_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="start_depth",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="track_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
