# Generated by Django 4.2.9 on 2024-05-24 16:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("smdb", "0054_status_remove_mission_status_mission_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quality_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("production_survey", "production_survey"),
                            ("use_with_caution", "use_with_caution"),
                            ("failed_survey", "failed_survey"),
                            ("do_not_use_survey", "do_not_use_survey"),
                            ("never_run", "never_run"),
                            ("test_survey", "test_survey"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="mission",
            name="status",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.AddField(
            model_name="mission",
            name="quality_categories",
            field=models.ManyToManyField(blank=True, to="smdb.quality_category"),
        ),
    ]
