#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python smdb/manage.py migrate
# https://stackoverflow.com/a/72206748/1281657
python smdb/manage.py runserver_plus --keep-meta-shutdown 0.0.0.0:8001
