log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

http:
  routers:
    web-secure-router:
      rule: "Host(`smdb.shore.mbari.org`)"
      # Use for testing on development system
      ##rule: "Host(`localhost`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      # https://doc.traefik.io/traefik/migration/v1-to-v2/#tls-configuration-is-now-dynamic-per-router
      tls:
        options: myTLSOptions

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

tls:
  certificates:
    # https://doc.traefik.io/traefik/master/https/tls/
    - certFile: /certs/smdb.crt
      keyFile: /certs/smdb.key
  options:
    myTLSOptions:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

##accessLog: {}
