version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/debug/django/Dockerfile
    image: smdb_debug_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
    volumes:
       # Edit to use directory on your host
      - /Users/mccann/docker_smdb_vol:/etc/smdb:z
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
      - "5678:5678"
    command: /start
    ##command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 smdb/manage.py runserver_plus 0.0.0.0:8000 --nothreading --noreload"]
     
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: smdb_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

##  docs:
##    image: smdb_local_docs
##    container_name: docs
##    build:
##      context: .
##      dockerfile: ./compose/local/docs/Dockerfile
##    env_file:
##      - ./.envs/.local/.django
##    volumes:
##      - ./docs:/docs:z
##      - ./config:/app/config:z
##      - ./smdb:/app/smdb:z
##    ports:
##      - "7000:7000"
##    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: smdb_local_node
    container_name: node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"
